name: Basic
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
    - uses: actions/checkout@v1
    - name: Install OpenCV
      uses: ./ # Uses an action in the root directory
      with:
        opencv-version: '4.0.0'
    - name: build application
      run: make